### ISSUE TITLE
A question for the filtered and uploaded stanfordcars dataset

### ISSUE THREAD

**Issue by e0jun** [RAIVNLab/neural-priming#2]
Hello authors
Thank you for your excellent work.

I have questions about the filtered and uploaded Stanfordcars dataset.
Some images are **truncated** when downloading this dataset from Google Drive. Is it right?

Please give me an answer to this.
I appreciate any help you can give me.

**Comment by vkramanuj** [comment]
This is a bug that we have also noted. The paper uses untruncated images. We fixed them recently in the google drive. If you notice any other data problem please file another issue! Thanks :-)
